version: '3'
services:
  gemini-telegram-bot:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=${HTTP_PROXY:-}
        - HTTPS_PROXY=${HTTPS_PROXY:-}
    volumes:
      - .:/app
    restart: unless-stopped